### ISSUE TITLE
Method Name Lowcase

### ISSUE THREAD

**Issue by ccccbjcn** [CCC-NULS/Nulstar#1]
Modules could register APIs name with capital letters. it needs not to transform them to lowercase.
The registered APIs parameters also need not to be transformed to lowercase.
https://github.com/CCC-NULS/Nulstar/blob/92c6e57f39abff11a3329577011c89ee33ec9f82/Libraries/Nulstar/NCore/NCoreService.cpp#L299
@Berzeck

**Comment by Berzeck** [comment]
@ccccbjcn 
I uploaded a new version on test server please test before I perform the commit.

**Comment by ccccbjcn** [comment]
@Berzeck 
I have tested the new version on test server. The APIs could be called successfully from external APP(I used chrome WebSock Client plugin).
Please refer to the blow link for test report detail.
https://github.com/CCC-NULS/Nulstar/blob/master/Documents/Test%20Reports/Test%20Report-20190716-Ray(CCC).docx
