### ISSUE TITLE
 loop will run at most once 

### ISSUE THREAD

**Issue by ccccbjcn** [CCC-NULS/Nulstar#5]
https://github.com/CCC-NULS/Nulstar/blob/0281cdf81bb2071760d8f99bb532572907e397fc/Modules/Nulstar/Connector/NConnectionController.cpp#L77
@Berzeck  This loop only run one time.

**Comment by Berzeck** [comment]
@ccccbjcn 
Thats OK for now because we are only processing 1 method per request. This may change in the future so I added the necessary structures tu support multiple requests per call. For now its just one request  method per call.
